//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPharmacieApi.Modeles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int IdCommande { get; set; }
        public string CodeCommande { get; set; }
        public string NomCommande { get; set; }
        public System.DateTime DateCommande { get; set; }
        public int QteCommande { get; set; }
        public double MontantCommande { get; set; }
        public int IdMedicament { get; set; }
    
        public virtual Commande Commande1 { get; set; }
        public virtual Commande Commande2 { get; set; }
        public virtual Medicament Medicament { get; set; }
    }
}
